language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - stable
  - nightly

# The main build
script:
  - cargo build
  - cargo build --examples
  - cargo test