[package]
name = "datafusion"
description = "DataFusion is a datasource-agnostic distributed query planning and execution framework for Rust"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>", "bgardner@squarelabs.net"]
documentation = "https://github.com/andygrove/datafusion-rs"
homepage = "https://github.com/andygrove/datafusion-rs"
repository = "https://github.com/andygrove/datafusion-rs"
license = "Apache-2.0"


[lib]
name = "datafusion"
path = "src/lib.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[dependencies]
csv = "1.0.0-beta.5"
futures = "0.1.14"
hyper = "0.11.2"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
#etcd = "0.8.0"
